
SS_HEARTBEAT_INTERVAL_TIME = 3 # in seconds
SS_AVAILABILITY_CHECKING_INTERVAL_TIME = 10 # in seconds

SS_WORKER_TASK_STATE_UPDATING_INTERVEL_TIME = 1


SS_ID_SEPERATOR = "---"


SS_MIN_TASK_DURATION = 60 # in seconds